project_id = "urshsiapemvfdxkqaiow"

[functions.epic-auth]
verify_jwt = false

[functions.pointclickcare-auth]
verify_jwt = false

[functions.virtual-card]
verify_jwt = false

[functions.manage-ehr-credentials]
verify_jwt = false

[functions.epic-jwks]
verify_jwt = false

[functions.stripe-connect]
verify_jwt = false
